apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentpeso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peso
  template:
    metadata:
      labels:
        app: peso
    spec:
      containers:
        - name: peso
          image: narirock2/dotnet_kubdev:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: peso
spec:
  selector:
    app: peso
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: LoadBalancer
